import { toast } from "sonner";

export type TailoredResume = {
  tailored_resume: {
    header: { name?: string; email?: string; phone?: string; location?: string };
    sections: {
      type: string;
      content?: string;
      items?: any[];
      categories?: Record<string, string[]>;
    }[];
  };
  sections: string[];
  section_reasons: Record<string, string>;
  template: string;
  filename: string;
  ats_score: { score: number; matched: string[]; missing: string[]; total_keywords: number };
};

export function buildResumePdfContent(result: TailoredResume): string {
  const h = result.tailored_resume.header || {};
  const lines: string[] = [];
  const hr = "─".repeat(70);

  // Header
  lines.push(h.name || "Your Name");
  const contactParts = [h.email, h.phone, h.location].filter(Boolean);
  if (contactParts.length) lines.push(contactParts.join("  |  "));
  lines.push(hr);

  for (const section of result.tailored_resume.sections) {
    lines.push("");
    lines.push(section.type.toUpperCase());
    lines.push(hr);

    if (section.type === "summary") {
      lines.push(section.content || "");
    } else if (section.type === "skills" && section.categories) {
      for (const [cat, skills] of Object.entries(section.categories)) {
        lines.push(`${cat}: ${(skills as string[]).join(", ")}`);
      }
    } else if (section.type === "experience" && section.items) {
      for (const exp of section.items) {
        lines.push("");
        lines.push(`${exp.title || ""} — ${exp.company || ""}`);
        if (exp.duration) lines.push(exp.duration);
        for (const b of (exp.bullets || [])) {
          lines.push(`  • ${b}`);
        }
      }
    } else if (section.type === "education" && section.items) {
      for (const edu of section.items) {
        lines.push(`${edu.degree || ""} — ${edu.institution || ""}`);
        if (edu.field) lines.push(`  Field: ${edu.field}`);
        if (edu.year) lines.push(`  Year: ${edu.year}`);
      }
    } else if (section.type === "projects" && section.items) {
      for (const proj of section.items) {
        lines.push("");
        lines.push(`${proj.name || ""}`);
        if (proj.description) lines.push(`  ${proj.description}`);
        if (proj.technologies?.length) lines.push(`  Tech: ${proj.technologies.join(", ")}`);
      }
    } else if (section.type === "certifications" && section.items) {
      for (const cert of section.items) {
        lines.push(`• ${cert.name || ""}${cert.issuer ? ` — ${cert.issuer}` : ""}`);
      }
    }
  }

  lines.push("");
  lines.push(`─── Generated by CareerPilot AI · ATS Score: ${result.ats_score.score}% ───`);
  return lines.join("\n");
}

export function buildHtmlResume(result: TailoredResume): string {
  const h = result.tailored_resume.header || {};
  const atsColor = result.ats_score.score >= 80 ? "#16a34a" : result.ats_score.score >= 60 ? "#2563eb" : "#7c3aed";

  let sectionsHtml = "";
  for (const section of result.tailored_resume.sections) {
    sectionsHtml += `<div class="section">
      <h2 class="section-title">${section.type.charAt(0).toUpperCase() + section.type.slice(1)}</h2>`;

    if (section.type === "summary") {
      sectionsHtml += `<p>${section.content || ""}</p>`;
    } else if (section.type === "skills" && section.categories) {
      sectionsHtml += `<div class="skills-grid">`;
      for (const [cat, skills] of Object.entries(section.categories)) {
        sectionsHtml += `<div><strong>${cat}:</strong> ${(skills as string[]).join(", ")}</div>`;
      }
      sectionsHtml += `</div>`;
    } else if (section.type === "experience" && section.items) {
      for (const exp of section.items) {
        sectionsHtml += `<div class="exp-item">
          <div class="exp-header">
            <strong>${exp.title || ""}</strong> — <span>${exp.company || ""}</span>
            ${exp.duration ? `<span class="duration">${exp.duration}</span>` : ""}
          </div>
          <ul>${(exp.bullets || []).map((b: string) => `<li>${b}</li>`).join("")}</ul>
        </div>`;
      }
    } else if (section.type === "education" && section.items) {
      for (const edu of section.items) {
        sectionsHtml += `<div class="edu-item">
          <strong>${edu.degree || ""}</strong> — <span>${edu.institution || ""}</span>
          ${edu.field ? `<div class="meta">Field: ${edu.field}</div>` : ""}
          ${edu.year ? `<div class="meta">Year: ${edu.year}</div>` : ""}
        </div>`;
      }
    } else if (section.type === "projects" && section.items) {
      for (const proj of section.items) {
        sectionsHtml += `<div class="proj-item">
          <strong>${proj.name || ""}</strong>
          ${proj.description ? `<p>${proj.description}</p>` : ""}
          ${proj.technologies?.length ? `<p class="tech">Tech: ${proj.technologies.join(", ")}</p>` : ""}
        </div>`;
      }
    } else if (section.type === "certifications" && section.items) {
      sectionsHtml += `<ul>${section.items.map((c: any) => `<li>${c.name || ""}${c.issuer ? ` — <em>${c.issuer}</em>` : ""}</li>`).join("")}</ul>`;
    }

    sectionsHtml += `</div>`;
  }

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${h.name || "Resume"}</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap');
  *{box-sizing:border-box;margin:0;padding:0}
  body{font-family:'Inter',sans-serif;font-size:11pt;color:#1a1a1a;background:#fff;max-width:210mm;margin:0 auto;padding:16mm 18mm}
  .header{text-align:center;border-bottom:2px solid #1a1a1a;padding-bottom:12px;margin-bottom:18px}
  .header h1{font-family:'Manrope',sans-serif;font-size:22pt;font-weight:800;letter-spacing:-0.5px}
  .header .contact{color:#444;font-size:9.5pt;margin-top:5px}
  .ats-badge{display:inline-block;background:${atsColor};color:#fff;font-size:8pt;padding:2px 8px;border-radius:99px;margin-top:6px;font-weight:600}
  .section{margin-bottom:16px}
  .section-title{font-family:'Manrope',sans-serif;font-size:10pt;font-weight:800;text-transform:uppercase;letter-spacing:1.5px;color:#1a1a1a;border-bottom:1px solid #e5e7eb;padding-bottom:3px;margin-bottom:8px}
  .exp-item,.edu-item,.proj-item{margin-bottom:10px}
  .exp-header{display:flex;align-items:baseline;flex-wrap:wrap;gap:4px}
  .exp-header strong{font-weight:600;font-size:10.5pt}
  .duration{margin-left:auto;color:#666;font-size:9pt}
  ul{padding-left:14px;margin-top:5px}
  li{margin-bottom:3px;font-size:10pt;line-height:1.45}
  .meta{color:#666;font-size:9pt;margin-top:2px}
  .tech{color:#555;font-size:9pt;font-style:italic;margin-top:3px}
  .skills-grid{display:grid;gap:4px}
  p{font-size:10pt;line-height:1.5;color:#222}
  @media print{body{padding:10mm 14mm}@page{margin:0;size:A4}}
</style>
</head>
<body>
  <div class="header">
    <h1>${h.name || "Your Name"}</h1>
    <div class="contact">${[h.email, h.phone, h.location].filter(Boolean).join("  ·  ")}</div>
    <span class="ats-badge">ATS Score: ${result.ats_score.score}%</span>
  </div>
  ${sectionsHtml}
</body>
</html>`;
}

export const downloadAsPdf = async (result: TailoredResume) => {
  const html = buildHtmlResume(result);
  
  // Create container
  const container = document.createElement("div");
  container.innerHTML = html;
  const bodyContent = container.querySelector("body")?.innerHTML || html;
  
  const element = document.createElement("div");
  element.innerHTML = bodyContent;
  element.style.padding = "20mm 20mm"; // page margin matching A4
  element.style.width = "210mm";
  element.style.backgroundColor = "#ffffff";
  element.style.color = "#1a1a1a";
  element.style.fontFamily = "'Inter', sans-serif";
  
  const loadScript = (url: string) => {
    return new Promise((resolve, reject) => {
      if ((window as any).html2pdf) {
        resolve((window as any).html2pdf);
        return;
      }
      const script = document.createElement("script");
      script.src = url;
      script.onload = () => resolve((window as any).html2pdf);
      script.onerror = reject;
      document.head.appendChild(script);
    });
  };

  try {
    toast.loading("Generating PDF...", { id: "pdf-gen" });
    const html2pdf = await loadScript("https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js") as any;
    
    // Ensure filename ends in .pdf
    const outputFilename = result.filename.replace(/\.(json|txt|html|pdf)$/i, "") + ".pdf";

    const opt = {
      margin:       [0, 0, 0, 0],
      filename:     outputFilename,
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2, useCORS: true, letterRendering: true },
      jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
    };
    
    await html2pdf().set(opt).from(element).save();
    toast.success("PDF downloaded successfully!", { id: "pdf-gen" });
  } catch (err) {
    console.error(err);
    toast.error("Failed to generate PDF. Triggering print dialog instead...", { id: "pdf-gen" });
    // Fallback: print window
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(html);
      printWindow.document.close();
      printWindow.focus();
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 500);
    }
  }
};

export const downloadAsWord = (result: TailoredResume) => {
  const html = buildHtmlResume(result);
  const docHtml = `<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns="http://www.w3.org/TR/REC-html40">
    <head><title>Resume</title><style>body { font-family: Arial, sans-serif; }</style></head>
    <body>${html}</body>
  </html>`;
  const blob = new Blob(['\ufeff' + docHtml], { type: "application/msword;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  
  // Ensure filename ends in .doc
  a.download = result.filename.replace(/\.(json|txt|html|pdf)$/i, "") + ".doc";
  a.click();
  URL.revokeObjectURL(url);
  toast.success("Resume Word file (.doc) downloaded!");
};

export const downloadAsText = (result: TailoredResume) => {
  const text = buildResumePdfContent(result);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  
  // Ensure filename ends in .txt
  a.download = result.filename.replace(/\.(json|html|pdf|doc)$/i, "") + ".txt";
  a.click();
  URL.revokeObjectURL(url);
  toast.success("Resume text file downloaded!");
};
