/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSkillGapRouteImport } from './routes/_app.skill-gap'
import { Route as AppRoadmapRouteImport } from './routes/_app.roadmap'
import { Route as AppResumeStudioRouteImport } from './routes/_app.resume-studio'
import { Route as AppResumeHistoryRouteImport } from './routes/_app.resume-history'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppJdAnalyzerRouteImport } from './routes/_app.jd-analyzer'
import { Route as AppInterviewPrepRouteImport } from './routes/_app.interview-prep'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCompanyIntelRouteImport } from './routes/_app.company-intel'
import { Route as AppCareerCoachRouteImport } from './routes/_app.career-coach'
import { Route as AppAtsAnalyzerRouteImport } from './routes/_app.ats-analyzer'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSkillGapRoute = AppSkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => AppRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeStudioRoute = AppResumeStudioRouteImport.update({
  id: '/resume-studio',
  path: '/resume-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppResumeHistoryRoute = AppResumeHistoryRouteImport.update({
  id: '/resume-history',
  path: '/resume-history',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppJdAnalyzerRoute = AppJdAnalyzerRouteImport.update({
  id: '/jd-analyzer',
  path: '/jd-analyzer',
  getParentRoute: () => AppRoute,
} as any)
const AppInterviewPrepRoute = AppInterviewPrepRouteImport.update({
  id: '/interview-prep',
  path: '/interview-prep',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanyIntelRoute = AppCompanyIntelRouteImport.update({
  id: '/company-intel',
  path: '/company-intel',
  getParentRoute: () => AppRoute,
} as any)
const AppCareerCoachRoute = AppCareerCoachRouteImport.update({
  id: '/career-coach',
  path: '/career-coach',
  getParentRoute: () => AppRoute,
} as any)
const AppAtsAnalyzerRoute = AppAtsAnalyzerRouteImport.update({
  id: '/ats-analyzer',
  path: '/ats-analyzer',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ats-analyzer': typeof AppAtsAnalyzerRoute
  '/career-coach': typeof AppCareerCoachRoute
  '/company-intel': typeof AppCompanyIntelRoute
  '/dashboard': typeof AppDashboardRoute
  '/interview-prep': typeof AppInterviewPrepRoute
  '/jd-analyzer': typeof AppJdAnalyzerRoute
  '/jobs': typeof AppJobsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/resume-history': typeof AppResumeHistoryRoute
  '/resume-studio': typeof AppResumeStudioRoute
  '/roadmap': typeof AppRoadmapRoute
  '/skill-gap': typeof AppSkillGapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/ats-analyzer': typeof AppAtsAnalyzerRoute
  '/career-coach': typeof AppCareerCoachRoute
  '/company-intel': typeof AppCompanyIntelRoute
  '/dashboard': typeof AppDashboardRoute
  '/interview-prep': typeof AppInterviewPrepRoute
  '/jd-analyzer': typeof AppJdAnalyzerRoute
  '/jobs': typeof AppJobsRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/resume-history': typeof AppResumeHistoryRoute
  '/resume-studio': typeof AppResumeStudioRoute
  '/roadmap': typeof AppRoadmapRoute
  '/skill-gap': typeof AppSkillGapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/ats-analyzer': typeof AppAtsAnalyzerRoute
  '/_app/career-coach': typeof AppCareerCoachRoute
  '/_app/company-intel': typeof AppCompanyIntelRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/interview-prep': typeof AppInterviewPrepRoute
  '/_app/jd-analyzer': typeof AppJdAnalyzerRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/resume-history': typeof AppResumeHistoryRoute
  '/_app/resume-studio': typeof AppResumeStudioRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_app/skill-gap': typeof AppSkillGapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ats-analyzer'
    | '/career-coach'
    | '/company-intel'
    | '/dashboard'
    | '/interview-prep'
    | '/jd-analyzer'
    | '/jobs'
    | '/notifications'
    | '/profile'
    | '/resume-history'
    | '/resume-studio'
    | '/roadmap'
    | '/skill-gap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/ats-analyzer'
    | '/career-coach'
    | '/company-intel'
    | '/dashboard'
    | '/interview-prep'
    | '/jd-analyzer'
    | '/jobs'
    | '/notifications'
    | '/profile'
    | '/resume-history'
    | '/resume-studio'
    | '/roadmap'
    | '/skill-gap'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/ats-analyzer'
    | '/_app/career-coach'
    | '/_app/company-intel'
    | '/_app/dashboard'
    | '/_app/interview-prep'
    | '/_app/jd-analyzer'
    | '/_app/jobs'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/resume-history'
    | '/_app/resume-studio'
    | '/_app/roadmap'
    | '/_app/skill-gap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/skill-gap': {
      id: '/_app/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof AppSkillGapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resume-studio': {
      id: '/_app/resume-studio'
      path: '/resume-studio'
      fullPath: '/resume-studio'
      preLoaderRoute: typeof AppResumeStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resume-history': {
      id: '/_app/resume-history'
      path: '/resume-history'
      fullPath: '/resume-history'
      preLoaderRoute: typeof AppResumeHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jd-analyzer': {
      id: '/_app/jd-analyzer'
      path: '/jd-analyzer'
      fullPath: '/jd-analyzer'
      preLoaderRoute: typeof AppJdAnalyzerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/interview-prep': {
      id: '/_app/interview-prep'
      path: '/interview-prep'
      fullPath: '/interview-prep'
      preLoaderRoute: typeof AppInterviewPrepRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/company-intel': {
      id: '/_app/company-intel'
      path: '/company-intel'
      fullPath: '/company-intel'
      preLoaderRoute: typeof AppCompanyIntelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/career-coach': {
      id: '/_app/career-coach'
      path: '/career-coach'
      fullPath: '/career-coach'
      preLoaderRoute: typeof AppCareerCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ats-analyzer': {
      id: '/_app/ats-analyzer'
      path: '/ats-analyzer'
      fullPath: '/ats-analyzer'
      preLoaderRoute: typeof AppAtsAnalyzerRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAtsAnalyzerRoute: typeof AppAtsAnalyzerRoute
  AppCareerCoachRoute: typeof AppCareerCoachRoute
  AppCompanyIntelRoute: typeof AppCompanyIntelRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInterviewPrepRoute: typeof AppInterviewPrepRoute
  AppJdAnalyzerRoute: typeof AppJdAnalyzerRoute
  AppJobsRoute: typeof AppJobsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumeHistoryRoute: typeof AppResumeHistoryRoute
  AppResumeStudioRoute: typeof AppResumeStudioRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppSkillGapRoute: typeof AppSkillGapRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAtsAnalyzerRoute: AppAtsAnalyzerRoute,
  AppCareerCoachRoute: AppCareerCoachRoute,
  AppCompanyIntelRoute: AppCompanyIntelRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInterviewPrepRoute: AppInterviewPrepRoute,
  AppJdAnalyzerRoute: AppJdAnalyzerRoute,
  AppJobsRoute: AppJobsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumeHistoryRoute: AppResumeHistoryRoute,
  AppResumeStudioRoute: AppResumeStudioRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppSkillGapRoute: AppSkillGapRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
